defaults:
  - model: samba_L
  - trainer: base
  - dataset: nasa_L
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

keep_checkpoint: True
gpu_devices: auto
log_graph: False

hydra:
  sweeper:
    params:
      dataset.resample_type_train: linear, random, anchors
  sweep:
    dir: outputs/ablation/resample/${now:%Y-%m-%d}/${now:%H-%M-%S}
